// <auto-generated />
using System;
using DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(QuanLyTienMatContext))]
    partial class QuanLyTienMatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.GiaoDich", b =>
                {
                    b.Property<int>("GiaoDichId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GiaoDichID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiaoDichId"));

                    b.Property<string>("ChungTuGoc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienGiai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("LoaiGiaoDich")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("NgayCt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayCT");

                    b.Property<string>("SoCt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SoCT");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SoTienBangChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDoiTuong")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TkdoiUng")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TKDoiUng");

                    b.HasKey("GiaoDichId")
                        .HasName("PK__GiaoDich__D8D14B310C589D28");

                    b.HasIndex(new[] { "SoCt" }, "UQ__GiaoDich__BC3D1CA82009D386")
                        .IsUnique()
                        .HasFilter("[SoCT] IS NOT NULL");

                    b.ToTable("GiaoDich", (string)null);

                    b.HasData(
                        new
                        {
                            GiaoDichId = 1,
                            NgayCt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoCt = "PT001",
                            SoTien = 10000000m,
                            TenDoiTuong = "Công ty ABC"
                        },
                        new
                        {
                            GiaoDichId = 2,
                            NgayCt = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoCt = "PC001",
                            SoTien = 2500000m,
                            TenDoiTuong = "Điện lực Hà Nội"
                        });
                });

            modelBuilder.Entity("DAL.Models.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiDungId"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("VaiTroId")
                        .HasColumnType("int")
                        .HasColumnName("VaiTroID");

                    b.HasKey("NguoiDungId")
                        .HasName("PK__NguoiDun__C4BBA4DD1C097B1D");

                    b.HasIndex("VaiTroId");

                    b.HasIndex(new[] { "TenNguoiDung" }, "UQ__NguoiDun__57E5A81D1AA6E4BB")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);

                    b.HasData(
                        new
                        {
                            NguoiDungId = 1,
                            MatKhau = "202CB962AC59075B964B07152D234B70",
                            TenNguoiDung = "admin",
                            VaiTroId = 1
                        });
                });

            modelBuilder.Entity("DAL.Models.VaiTro", b =>
                {
                    b.Property<int>("VaiTroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VaiTroID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaiTroId"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VaiTroId")
                        .HasName("PK__VaiTro__477581362A1144F7");

                    b.HasIndex(new[] { "TenVaiTro" }, "UQ__VaiTro__1DA558144CD9EAE8")
                        .IsUnique();

                    b.ToTable("VaiTro", (string)null);

                    b.HasData(
                        new
                        {
                            VaiTroId = 1,
                            TenVaiTro = "Admin"
                        },
                        new
                        {
                            VaiTroId = 2,
                            TenVaiTro = "Kế toán"
                        });
                });

            modelBuilder.Entity("DAL.Models.NguoiDung", b =>
                {
                    b.HasOne("DAL.Models.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("VaiTroId")
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("DAL.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
